static_library("starboard_platform") {
  check_includes = false

  sources = [
    "application_sdl.cc",
    "application_sdl.h",
    "main.cc",
    "player_set_bounds.cc",
    "shared_av_experiment.h",
    "starfish_av_components.cc",
    "starfish_av_components.h",
    "starfish_av_session_state.h",
    "starfish_audio_timing.h",
    "starfish_audio_session.h",
    "starfish_opus_configuration.h",
    "starfish_playback_rate.h",
    "starfish_playback_rate.cc",
    "starfish_video_configuration.h",
    "starfish_video_decoder.cc",
    "starfish_video_decoder.h",
    "webos_media_capabilities.cc",
    "webos_video_preference.cc",
    "webos_ui_preferences.cc",
    "webos_ui_preferences.h",
    "webos_media_capabilities.h",
    "webos_media_diagnostics.cc",
    "webos_media_diagnostics.h",
    "webos_media_diagnostics_bridge.h",
    "webos_media_report.cc",
    "webos_capability_test.cc",
    "webos_capability_test.h",
    "webos_capability_process.h",
    "webos_media_clipboard.cc",
    "webos_media_report.h",
    "webos_build_metadata.h",
    "webos_lifecycle.h",
    "webos_lifecycle.cc",
    "window_create.cc",
    "window_destroy.cc",
    "window_get_platform_handle.cc",
    "window_get_size.cc",
    "window_internal.h",
    "//starboard/linux/x64x11/public_system_properties.cc",
    "//starboard/linux/x64x11/system_get_property.cc",
    "//starboard/linux/x64x11/system_get_property_impl.cc",
    "//starboard/linux/x64x11/system_get_property_impl.h",
    "//starboard/linux/x64x11/system_properties.h",
    "//starboard/shared/libjpeg/image_decode.cc",
    "//starboard/shared/libjpeg/image_is_decode_supported.cc",
    "//starboard/shared/libjpeg/jpeg_image_decoder.cc",
    "//starboard/shared/libjpeg/jpeg_image_decoder.h",
    "//starboard/shared/starboard/link_receiver.cc",
  ]

  public_deps = [
    "//starboard/egl_and_gles",
    "//starboard/linux/shared:starboard_platform",
    "//starboard/shared/starboard/player:video_dmp",
  ]
  deps = [ "//third_party/libjpeg-turbo:libjpeg" ]
  configs += [ "//starboard/build/config:starboard_implementation" ]
}
